name: منبع جدید
description: پیشنهاد کانال یا لینک منبع جدید
labels: [source]
body:
  - type: input
    id: url
    attributes:
      label: لینک منبع
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: چرا مفید است
