name: "Let's SiNAVM!"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

concurrency:
  group: "sinavm-full"
  cancel-in-progress: true

jobs:
  sinavm-full:
    runs-on: ubuntu-latest
    env:
      PRIVATE_LINK_SiNAVM_1: ${{ secrets.PRIVATE_LINK_SiNAVM_1 }}
      PRIVATE_LINK_SiNAVM_2: ${{ secrets.PRIVATE_LINK_SiNAVM_2 }}
      PRIVATE_LINK_SiNAVM_3: ${{ secrets.PRIVATE_LINK_SiNAVM_3 }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # این خط اضافه شده است
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies for HiddifyCli
        run: |
          sudo apt-get update
          sudo apt-get install -y curl tar 

      - name: Execute PHP script
        run: |
          set -euo pipefail
          git config pull.rebase true
          git config rebase.autoStash true
          git pull --rebase 

          php -d display_errors get.php
          php -d display_errors config-test.php || true 
          php -d display_errors channelsAssets.php
          php -d display_errors duplicate.php
          php -d display_errors sort.php
          php -d display_errors toSingbox.php
          php -d display_errors toClashSurfboard.php
          php -d display_errors hiddifyWarp.php

          git config --global user.email "sina.bb2006@gmail.com"
          git config --global user.name "sinavm"
          git config credential.helper store 


          for i in {1..3}; do
            git pull --rebase 
            git add -A 

            commit_message="🤴‍♂️ Servers Updated - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
            git commit -m "$commit_message" --allow-empty
            git push && break || sleep 5 
          done

  sinavm-lite:
    runs-on: ubuntu-latest
    needs: sinavm-full
    env:
      PRIVATE_LINK_SiNAVM_1: ${{ secrets.PRIVATE_LINK_SiNAVM_1 }}
      PRIVATE_LINK_SiNAVM_2: ${{ secrets.PRIVATE_LINK_SiNAVM_2 }}
      PRIVATE_LINK_SiNAVM_3: ${{ secrets.PRIVATE_LINK_SiNAVM_3 }}
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # این خط اضافه شده است
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Dependencies for HiddifyCli
        run: |
          sudo apt-get update
          sudo apt-get install -y curl tar

      - name: Execute PHP script
        run: |
          set -euo pipefail 
          git config pull.rebase true
          git config rebase.autoStash true
          git pull --rebase

          cd lite
          php -d display_errors ../get.php
          php -d display_errors ../config-test.php || true 
          php -d display_errors duplicate.php
          php -d display_errors sort.php
          php -d display_errors ../toSingbox.php
          php -d display_errors ../toClashSurfboard.php

          git config --global user.email "sina.bb2006@gmail.com"
          git config --global user.name "sinavm"
          git config credential.helper store

          for i in {1..3}; do
            git pull --rebase 
            git add -A 

            commit_message="👸 Lite Servers Updated - $(TZ='Asia/Tehran' date '+%Y-%m-%d %H:%M:%S')"
            git commit -m "$commit_message" --allow-empty
            git push && break || sleep 5 
          done
